### ISSUE TITLE
heredocs aren't properly closed during indent fomartting

### ISSUE THREAD

**Issue by nozaq** [hashicorp/hcl2#106]
hclfmt failed to properly format indentation when a block contains two or more heredocs.
related issue: https://github.com/hashicorp/terraform/issues/21434

Consider the following HCL code.

```
$ cat ../test.tf                        
foo {
bar = <<EOT
Foo bar baz
EOT
baz = <<EOT
Foo bar baz
EOT
}

baz {
default = "string"
}
```

When pass that file to hclfmt, the output of `baz` block is not indented as expected.

```
$ go run ./cmd/hclfmt/main.go ../test.tf
foo {
  bar = <<EOT
Foo bar baz
EOT
  baz = <<EOT
Foo bar baz
EOT
}

baz {
default = "string"
}
```

The expected output is:

```
$ go run ./cmd/hclfmt/main.go ../test.tf
foo {
  bar = <<EOT
Foo bar baz
EOT
  baz = <<EOT
Foo bar baz
EOT
}

baz {
  default = "string"
}
```

It seems [inHeredoc flag](https://github.com/hashicorp/hcl2/blob/master/hclwrite/format.go#L57) is not set to false even after processing `foo` block. This could be because `formatIndent()` function expects `TokenOHeredoc` and `TokenCHeredoc` appear in different lines, while `linesForFormat` function put all tokens between `TokenOHeredoc` and `TokenCHeredoc` in the same `formatLine` instance.

I'm new to this codebase, so the above analysis could be completely wrong though...

**Comment by pselle** [comment]
Thanks for finding and fixing this! I've merged your change into master, and tested upgrading terraform with this change, but it doesn't seem to fix the upstream issue as yet. That said, this issue can be closed, and thank you for moving us closer to the solution!
