### ISSUE TITLE
Clarify whether tabs are accepted or not

### ISSUE THREAD

**Issue by jen20** [hashicorp/hcl2#123]
The specification (here) reads: https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md#comments-and-whitespace

However, this is contradicted both by this closed issue: https://github.com/hashicorp/hcl2/issues/2, and the implementation in Terraform 0.12 which accepts tabs without issue.

Which part is correct here?

**Comment by apparentlymart** [comment]
This indeed changed quite late on to allow tabs, in return for a more complicated idea of how we count columns for source location references. The specification is lagging behind the implementation.

**Comment by jen20** [comment]
Thanks for the clarification.
