### ISSUE TITLE
feat: struct field tag should support both block and optional

### ISSUE THREAD

**Issue by detailyang** [hashicorp/hcl2#96]
Hello.

Now the hcl cannot set optional block via the struct tag as below:

````golang
type Block struct {}
type Object struct {
	Block    Block    `hcl:"block,block,optional"`
}
````

**Comment by apparentlymart** [comment]
Hi @detailyang,

Currently the way to specify that is to make the field have type `*Block`, so that `gohcl` can set it to nil to indicate when the nested block isn't present.

**Comment by detailyang** [comment]
@apparentlymart Thanks. It works :)
